### ISSUE TITLE
The search_paths in lwoObject has error

### ISSUE THREAD

**Issue by amyaimei** [douglaskastle/blender-import-lwo#10]
At first, I think the indentation is wrong at the line paths.append(y).  I adjusted the indentation but it did not pickup the path I entered.  I modified the code as below to pickup the path I entered.  Please review if it is correct.
 
    def search_paths(self):
        paths = [self.dirpath]
        for s in self.ch.search_paths:
            if not re.search("^/", s) and not re.search("^.:", s):
                x = os.path.join(self.dirpath, s)
                y = os.path.abspath(x)
                paths.append(y)
            else:
                paths.append(s)
        return paths

**Comment by douglaskastle** [comment]
yes the first append is at the wrong indentation, unsure if the second would be there, checking now. Here I am trying to use valid search paths only, but even if it is invalid, the path won't yield a success when looking for files

**Comment by douglaskastle** [comment]
ok it was it.  I have made the whole change in full and re-released the addon.

https://github.com/nangtani/blender-import-lwo/releases/tag/v1.4.3

Thanks for the bug report.  Please feel free to report any more, if possible with an offending lwo, as I am short of those.
