### ISSUE TITLE
Vertex Colors are not imported

### ISSUE THREAD

**Issue by Alexxkrehmen** [douglaskastle/blender-import-lwo#24]
The vertex colors are properly parsed from the LWO file, but they are not assigned anywhere to the generated mesh.

See construct_mesh.py line 243 and 244 :
the vertex color are converted, the color map is created into the mesh... but the colors are not assigned to the color map.

**Comment by davekeeshan** [comment]
Change merged, but also code enhanced to use an enumerate for the loop: 

[#3707e2aff2bada9697f79294849248fec5379cd3](https://github.com/nangtani/blender-import-lwo/commit/3707e2aff2bada9697f79294849248fec5379cd3)

**Comment by Alexxkrehmen** [comment]
Thanks ! I was about to suggest this upgrade ;)
