### ISSUE TITLE
Any chance to have LWO export add-on / option ?

### ISSUE THREAD

**Issue by motorsep** [douglaskastle/blender-import-lwo#26]
Perhaps it's a pipedream, but I gotta ask - would it be possible for you to create LWO export option or LWO export add-on ?

It would be useful to Doom 3 modding community as Doom 3 engine uses LWO models (static meshes). LWO format is probably from that era (2004-ish).

**Comment by davekeeshan** [comment]
Sorry, exporting is a whole other effort from importing, I personally won't be doing that. However feel free to fork and have a look.

**Comment by Donald-Drennan** [comment]
There was one several years ago. You may have to use a previous version of
Blender.
