### ISSUE TITLE
Special characters in filename

### ISSUE THREAD

**Issue by RedTopper** [douglaskastle/blender-import-lwo#8]
If an image filename has special characters (in particular, brackets), the plugin fails to find the corresponding images for the LWO file due to the name being parsed as regex.

I was able to get a model to load by changing
```py
if re.search(imagefile, f, re.I):
```
to
```py
if re.search(re.escape(imagefile), f, re.I):
```
in https://github.com/douglaskastle/blender-import-lwo/blob/master/io_import_scene_lwo/lwoObject.py#L1150

... but I'm not sure if that's a good approach.

Here's the troublesome filenames:
```
Hgn_battlecruiser_badge_export[1].bmp
Hgn_battlecruiser_badge_export[1]SPEC.bmp
etc...
```

**Comment by douglaskastle** [comment]
Thanks so much for using the plugin and reporting the issue you have seen, with suggested fix.

I have just folded that fix back into the master repo:
6a29434c4552e84bddaf87fc18e45fbaf761687b

https://github.com/douglaskastle/blender-import-lwo/commit/6a29434c4552e84bddaf87fc18e45fbaf761687b

**Comment by douglaskastle** [comment]
Fixed contained in this release:

https://github.com/douglaskastle/blender-import-lwo/releases/tag/v1.4.1
